version: '3.8'

services:
  app:
    build: .
    container_name: meu-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:15
    container_name: meu-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=teste123
      - POSTGRES_DB=primeirodockerizado
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: